<?php

/**
 * @file
 * Primary module hooks for title_cases module.
 */

use Drupal\Core\Render\Markup;
use Drupal\title_cases\Controller\TitleCasesController as TitleCases;

/**
 * Implements hook_preprocess_node().
 *
 *   Returns the node title when title printed in the node template.
 */
function title_cases_preprocess_node__teaser(&$vars) {
  /** @var \Drupal\node\Entity\Node $vars['node'] */
  // AP Title Case for all node titles.
  $vars['label'] = TitleCases::titleCasesNodeTitle($vars);  
}

/**
 * Implements hook_preprocess_page_title().
 */
function title_cases_preprocess_page_title(&$vars) {
  /** @var \Drupal\node\Entity\Node $node */
  $node = \Drupal::request()->attributes->get('node');
  $vars['node'] = $node;

  // AP Title Case for all node titles.
  if (isset($node)) {
    $vars['title'] = TitleCases::titleCasesNodeTitle($vars);
  }
}

/**
 * Implements hook_preprocess_html().
 */
function title_cases_preprocess_html(&$vars) {
  /** @var \Drupal\node\Entity\Node $node */
  $html_title = \Drupal::config('title_cases.settings')->get('html_title');
  if ($html_title == TRUE) {
    $node = \Drupal::request()->attributes->get('node');

    // AP Title Case for all node titles.
    if (isset($node)) {
      $html_title = \Drupal::config('title_cases.settings')->get('html_title');
      $vars['head_title'] = Markup::create(TitleCases::titleCasesApTitle($node));
    }
  }
}
