# Schema for the configuration files of the Title Cases module.
title_cases.settings:
  type: config_object
  label: 'Title Cases settings'
  mapping:
    style_guide:
      type: array
      label: 'Style Guide'
    node_types:
      type: array
      label: 'Content Types'
